### ISSUE TITLE
RST/HAZ Layer is preventing pop-ups in New Web Map Viewer and Dashboards

### ISSUE THREAD

**Issue by pjdohertygis** [pjdohertygis/WideAreaSearchTemplates#212] opened 2022-03-23 04:49 UTC
@afackler ​ - It appears that the RST / HAZ layers are now causing an issue where no layers in the Dashboard or new Web Map Viewer can open pop-ups if the RST/HAZ layers are turned on. They still work in Classic and Web AppBuilder (older Javascript).

Something about the symbology that it does not like and since the release it does not work at all. Once you turn the layer off in the TOC, you can get pop-ups from other layers. 

Note: We also suspect this was causing issues with the Smart Editor prior to the release (where polygons could not be edited more than once), but that is now fixed. 

We will want to report and turn off RST in all maps for now. 

@CLivingstone FYI

**Comment by afackler** [comment] 2022-03-23 14:20
Just got off the phone with Esri, case **#03025894**.

Issue was happening in the sandbox as well. I sent them the links to the layers/ map to test on their end. Some observations:
- Issue only happened when views were turned on. I took out all the views and put in the master feature layer and could not reproduce, but when I added the views back in and turned them on the issue came back.
- I was using Edge and issue was reproducible in Chrome too (according to tech support)
- They mentioned this could be a release issue as we haven't noticed this since last night

**Comment by pjdohertygis** [comment] 2022-03-23 14:35
It would be good to narrow down if it is all feature layer views, or just when a feature layer view has a duplicate feature layer view or feature layer in the web map with the same geometry.

**Comment by afackler** [comment] 2022-03-23 17:03
After some testing, I found that the feature layer views that are causing the issue are all **not editable**. I added the views that were editable and did not experience the issue. Later I switched one of the views to editable and the issue vanished.

**Comment by afackler** [comment] 2022-03-25 19:13
Esri was able to replicate this issue and this bug has been fixed in a recent AGOL patch. It is suspected that the AGOL update was to blame.

**Closed by afackler** 2022-03-25 19:13 UTC
Labels: Bug, Dashboard, ArcGIS Online
